# Generated by Django 3.1 on 2020-08-20 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField(blank=True, verbose_name='patients id')),
                ('pregnancies', models.PositiveSmallIntegerField(verbose_name='number of pregnancies')),
                ('glucose', models.IntegerField(verbose_name='blood glucose')),
                ('blood_pressure', models.IntegerField(verbose_name='blood pressure')),
                ('skin_thickness', models.IntegerField(verbose_name='skin thickness')),
                ('insulin', models.IntegerField(verbose_name='insulin levels')),
                ('bmi', models.FloatField(verbose_name='body mass index')),
                ('dpf', models.FloatField(verbose_name='diabetes pedigree function')),
                ('age', models.IntegerField(verbose_name='age')),
                ('raw_outcome', models.FloatField(blank=True, verbose_name='raw output from model')),
                ('expected_class_outcome', models.IntegerField(blank=True, verbose_name='binary class predicted outcome')),
                ('actual_outcome', models.IntegerField(blank=True, verbose_name='tested outcome')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
